name: Build Firmware

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [LokDecoder, SoundDecoder, FunctionDecoder, AllInOne]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio

    - name: Cache PlatformIO dependencies
      uses: actions/cache@v4
      with:
        path: firmware/.pio
        key: ${{ runner.os }}-${{ hashFiles('firmware/platformio.ini') }}

    - name: Prepare Example ${{ matrix.example }}
      run: python scripts/prepare_example.py ${{ matrix.example }}

    - name: Build DCC
      run: |
        pio run -d firmware -e xiao_dcc
        mv firmware/.pio/build/xiao_dcc/firmware.uf2 firmware/Apollo-${{ matrix.example }}-dcc.uf2

    - name: Build MM
      run: |
        pio run -d firmware -e xiao_mm
        mv firmware/.pio/build/xiao_mm/firmware.uf2 firmware/Apollo-${{ matrix.example }}-mm.uf2

    - name: Archive Firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ matrix.example }}
        path: firmware/Apollo-*.uf2

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    permissions:
      contents: write
    steps:
    - name: Download LokDecoder Firmware
      uses: actions/download-artifact@v4
      with:
        name: firmware-LokDecoder
        path: dist

    - name: Download SoundDecoder Firmware
      uses: actions/download-artifact@v4
      with:
        name: firmware-SoundDecoder
        path: dist

    - name: Download FunctionDecoder Firmware
      uses: actions/download-artifact@v4
      with:
        name: firmware-FunctionDecoder
        path: dist

    - name: Download AllInOne Firmware
      uses: actions/download-artifact@v4
      with:
        name: firmware-AllInOne
        path: dist

    - name: Upload Firmware to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.uf2
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
