name: Build Firmware

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        protocol: [dcc, mm]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio

    - name: Cache PlatformIO dependencies
      uses: actions/cache@v4
      with:
        path: firmware/.pio
        key: ${{ runner.os }}-${{ hashFiles('firmware/platformio.ini') }}

    - name: Build Firmware (${{ matrix.protocol }})
      run: pio run -d firmware -e xiao_${{ matrix.protocol }}

    - name: Archive Firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ matrix.protocol }}
        path: firmware/.pio/build/xiao_${{ matrix.protocol }}/firmware.uf2

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    permissions:
      contents: write
    steps:
    - name: Download DCC Firmware
      uses: actions/download-artifact@v4
      with:
        name: firmware-dcc
        path: firmware-dcc

    - name: Download MM Firmware
      uses: actions/download-artifact@v4
      with:
        name: firmware-mm
        path: firmware-mm

    - name: Upload DCC Firmware to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: firmware-dcc/firmware.uf2
        asset_name: xiao_dcc.uf2
        tag: ${{ github.ref }}
        overwrite: true

    - name: Upload MM Firmware to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: firmware-mm/firmware.uf2
        asset_name: xiao_mm.uf2
        tag: ${{ github.ref }}
        overwrite: true
